name: Cloudflare Pages Branch Alias
description:
  A GitHub Action that generates a valid branch alias for Cloudflare Pages
  deployments from a Git branch name.
author: Michael Schnerring <3743342+schnerring@users.noreply.github.com>

branding:
  icon: git-branch
  color: orange

inputs:
  git-branch:
    required: true
    description: Git branch name

outputs:
  branch-alias:
    description: Branch alias suitable for Cloudflare Pages deployment

runs:
  using: node24
  main: dist/index.js
